# Configure this Discovery Server


eureka:
  datacenter: Main
  environment: prod
  instance:
    hostname: localhost
  client:  
    registerWithEureka: false
    fetchRegistry: false
     
server:
  port: 2030   # HTTP (Tomcat) port


spring:
  thymeleaf:
    enabled: false     # Disable Thymeleaf 